version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverlessResumeApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l3rux56u1de1"
s3_prefix = "serverlessResumeApi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
